name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Iniciando login en Docker Hub"
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: |
          docker build -t tavo0597/docker-graphql:0.0.2 .

      - name: Push Docker Image
        run: |
          docker push tavo0597/docker-graphql:0.0.2 .
